MovieProject.UI/Controllers/FilmController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using MovieProject.Entity.Entities;
using MovieProject.UI.DTOs.Films;
using Newtonsoft.Json;
using System.Text;

namespace MovieProject.UI.Controllers
{
    public class FilmController : Controller
    {
        private readonly IHttpClientFactory _httpClientFactory;
        public FilmController(IHttpClientFactory httpClientFactory)
        {
            _httpClientFactory = httpClientFactory;
        }
        public async Task<IActionResult> Index()
        {
            var client = _httpClientFactory.CreateClient();
            var responseMessage = await client.GetAsync("https://localhost:7096/api/Film");

            if (responseMessage.IsSuccessStatusCode)
            {
                var jsonData = await responseMessage.Content.ReadAsStringAsync();
                var hospitals = JsonConvert.DeserializeObject<List<ResultFilmDto>>(jsonData);

                return View(hospitals);
            }

            return View();
        }
        [HttpGet]
        public async Task<IActionResult> Create()
        {
            var client = _httpClientFactory.CreateClient();

            // Kategorileri ve aktörleri al
            var categoryResponse = await client.GetAsync("https://localhost:7096/api/Category");
            var actorResponse = await client.GetAsync("https://localhost:7096/api/Actor");

            if (categoryResponse.IsSuccessStatusCode)
            {
               var categoryJson = await categoryResponse.Content.ReadAsStringAsync();
               var actorJson = await actorResponse.Content.ReadAsStringAsync();

                var categories = JsonConvert.DeserializeObject<List<Category>>(categoryJson);
                var actors = JsonConvert.DeserializeObject<List<Actor>>(actorJson);

                var viewModel = new FilmAddDto
                {
                    Categories = categories,
                    Actors = actors
                   
                };
                return View(viewModel);
            }

            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Create(FilmAddDto createhospitalDto)
        {
            var client = _httpClientFactory.CreateClient();
            var categoryResponse = await client.GetAsync("https://localhost:7096/api/Category");
            var actorResponse = await client.GetAsync("https://localhost:7096/api/Actor");
            var jsonData = JsonConvert.SerializeObject(createhospitalDto);
            StringContent stringContent = new StringContent(jsonData, Encoding.UTF8, "application/json");
            var responseMessage = await client.PostAsync("https://localhost:7096/api/Film/CreateFilm", stringContent);
            if (responseMessage.IsSuccessStatusCode)
            {
                return RedirectToAction("Index");
            }
            var categoryJson = await categoryResponse.Content.ReadAsStringAsync();
            var actorJson = await actorResponse.Content.ReadAsStringAsync();

            var categories = JsonConvert.DeserializeObject<List<Category>>(categoryJson);
            var actors = JsonConvert.DeserializeObject<List<Actor>>(actorJson);

            var viewModel = new FilmAddDto
            {
                Categories = categories,
                Actors = actors

            };
            return View(viewModel);
        }
        [HttpGet]
        public async Task<IActionResult> Update(int id)
        {
            var client = _httpClientFactory.CreateClient();
            var responseMessage = await client.GetAsync($"https://localhost:7096/api/Film/{id}");
            var categoryResponse = await client.GetAsync("https://localhost:7096/api/Category");
            var actorResponse = await client.GetAsync("https://localhost:7096/api/Actor");


            if (responseMessage.IsSuccessStatusCode)
            {
                var categoryJson = await categoryResponse.Content.ReadAsStringAsync();
                var actorJson = await actorResponse.Content.ReadAsStringAsync();
                var jsonData = await responseMessage.Content.ReadAsStringAsync();
                var values = JsonConvert.DeserializeObject<FilmUpdateDto>(jsonData);
                var categories = JsonConvert.DeserializeObject<List<Category>>(categoryJson);
                var actors = JsonConvert.DeserializeObject<List<Actor>>(actorJson);
                values.Actors = actors;
                values.Categories = categories;
                return View(values);
            }
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Update(FilmUpdateDto hospitalUpdateDto)
        {
            var client = _httpClientFactory.CreateClient();
            var jsonData = JsonConvert.SerializeObject(hospitalUpdateDto);
            StringContent stringContent = new StringContent(jsonData, Encoding.UTF8, "application/json");
            var responseMessage = await client.PutAsync("https://localhost:7096/api/Film/UpdateFilm", stringContent);
            if (responseMessage.IsSuccessStatusCode)
            {
                return RedirectToAction("Index");
            }
            return View();
        }

        public async Task<IActionResult> Delete(int id)
        {
            var client = _httpClientFactory.CreateClient();
            var responseMessage = await client.DeleteAsync($"https://localhost:7096/api/Film/DeleteFilm/{id}");
            if (responseMessage.IsSuccessStatusCode)
            {
                return RedirectToAction("Index");
            }
            return View();
        }
    }
}

MovieProject.UI/Views/Film/Create.cshtml
@model FilmAddDto

<div class="content">
    <div class="container-fluid">
        <h4 class="page-title">Ana Sayfa Hakkımızda İşlemleri</h4>
        <div class="row">
            <div class="col-md-12">
                <form method="post" asp-action="Create" asp-controller="Film">
                    <div class="card">
                        <div class="card-header">
                            <div class="card-title">Film Ekleme Sayfası</div>
                        </div>
                        <div class="card-body">
                            <div class="form-group">
                                <label for="Title">Film Adı Giriniz</label>
                                <input type="text" class="form-control" asp-for="Title">
                            </div>
                        </div>
                        <div class="card-body">
                            <div class="form-group">
                                <label for="ReleaseDate">Vizyon Tarihi Giriniz</label>
                                <input type="date" class="form-control" asp-for="ReleaseDate">
                            </div>
                        </div>
                        <div class="card-body">
                            <div class="form-group">
                                <label for="CategoryId">Kategori Seçiniz</label>
                                <select class="form-control" asp-for="CategoryId" asp-items="@(new SelectList(Model.Categories,"CategoryId","Name"))">
                                    <option value="">-- Kategori Seçiniz --</option>
                                </select>
                            </div>
                        </div>
                        @* <div class="card-body">
                            <div class="form-group">
                                <label for="ActorId">Aktör Seçiniz</label>
                                <select class="form-control" asp-for="ActorId" asp-items="@(new SelectList(ViewBag.ActorList, "ActorId", "Name"))">
                                    <option value="">-- Aktör Seçiniz --</option>
                                </select>
                            </div>
                        </div> *@
                        <div class="card-action">
                            <button class="btn btn-primary">Kaydet</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

MovieProject.UI/Views/Film/Index.cshtml
 @model List<ResultFilmDto>

<table id="hospitalTable" class="table table-bordered">
    <thead>
        <tr>
            <th>Film Adı</th>
            <th>Çıkış Tarihi</th>
            <th>Kategorisi</th>
            <th>İşlemler</th>
            <th>İşlemler</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>@item.Title</td>
                <td>@item.ReleaseDate</td>
                <td>@item.Category.Name</td>
                <td>
                    @foreach (var actor in item.Actors)
                    {
                        <span>,@actor.Name</span>
                    }
                </td>
                <td><a asp-action="Update" asp-controller="Film" asp-route-id="@item.FilmId" class="btn mb-1 btn-rounded btn-outline-info">Güncelle</a></td>
                <td><a asp-action="Delete" asp-controller="Film" asp-route-id="@item.FilmId" class="btn mb-1 btn-rounded btn-outline-danger">Sil</a></td>
            </tr>
        }
    </tbody>
</table>

<a asp-action="Create" asp-controller="Film" class="btn mb-1 btn-rounded btn-outline-info">Yeni Film Ekle</a>

MovieProject.UI/Views/Film/Update.cshtml
@model FilmUpdateDto

<div class="content">
    <div class="container-fluid">
        <h4 class="page-title">Ana Sayfa Hakkımızda İşlemleri</h4>
        <div class="row">
            <div class="col-md-12">
                <form method="post" asp-action="Update" asp-controller="Film">
                    <div class="card">
                        <input type="hidden" asp-for="FilmId"/>
                        <div class="card-header">
                            <div class="card-title">Film Güncelleme Sayfası</div>
                        </div>
                        <div class="card-body">
                            <div class="form-group">
                                <label for="Title">Film Adı Giriniz</label>
                                <input type="text" class="form-control" asp-for="Title">
                            </div>
                        </div>
                        <div class="card-body">
                            <div class="form-group">
                                <label asp-for="ReleaseDate" for="defaultFormControlInput" class="form-label">Başlangıç Tarihi</label>
                                <input asp-for="ReleaseDate" type="date" class="form-control mb-3" id="defaultFormControlInput" placeholder="Lütfen başlık giriniz." aria-describedby="defaultFormControlHelp">
                                <span asp-validation-for="ReleaseDate" class="text-danger"></span>
                            </div>
                        </div>
                        <div class="card-body">
                            <div class="form-group">
                                <label for="CategoryId">Kategori Seçiniz</label>
                                <select class="form-control" asp-for="CategoryId" asp-items="@(new SelectList(Model.Categories,"CategoryId","Name"))">
                                    <option value="">-- Kategori Seçiniz --</option>
                                </select>
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="form-label text-right">Ekstra Malzemeler:</label>
                            <div class="form-check">
                                @foreach (var extra in Model.Actors)
                                {
                                    <div class="form-check">
                                        <input type="checkbox" id="extra-@extra.ActorId" class="form-check-input" name="SelectedActors" value="@extra.ActorId" @(Model.SelectedActors != null && Model.SelectedActors.Contains(extra.ActorId) ? "checked" : "")>
                                        <label for="extra-@extra.ActorId" class="form-check-label">@extra.Name</label>
                                    </div>
                                }
                            </div>
                        </div>
                        @* <div class="card-body">
                        <div class="form-group">
                        <label for="ActorId">Aktör Seçiniz</label>
                        <select class="form-control" asp-for="ActorId" asp-items="@(new SelectList(ViewBag.ActorList, "ActorId", "Name"))">
                        <option value="">-- Aktör Seçiniz --</option>
                        </select>
                        </div>
                        </div> *@
                        <div class="card-action">
                            <button class="btn btn-primary">Kaydet</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>