MovieProject.UI/Controllers/ActorController.cs
using Microsoft.AspNetCore.Mvc;
using MovieProject.UI.DTOs.Actors;
using Newtonsoft.Json;
using System.Text;

namespace MovieProject.UI.Controllers
{
    public class ActorController : Controller
    {
        private readonly IHttpClientFactory _httpClientFactory;
        public ActorController(IHttpClientFactory httpClientFactory)
        {
            _httpClientFactory = httpClientFactory;
        }
        public async Task<IActionResult> Index()
        {
            var client = _httpClientFactory.CreateClient();
            var responseMessage = await client.GetAsync("https://localhost:7096/api/Actor");

            if (responseMessage.IsSuccessStatusCode)
            {
                var jsonData = await responseMessage.Content.ReadAsStringAsync();
                var actors = JsonConvert.DeserializeObject<List<ResultActorDto>>(jsonData);

                return View(actors);
            }

            return View();
        }
        [HttpGet]
        public async Task<IActionResult> Create()
        {

            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Create(ActorAddDto createactorDto)
        {
            var client = _httpClientFactory.CreateClient();
            var jsonData = JsonConvert.SerializeObject(createactorDto);
            StringContent stringContent = new StringContent(jsonData, Encoding.UTF8, "application/json");
            var responseMessage = await client.PostAsync("https://localhost:7096/api/Actor/CreateActor", stringContent);
            if (responseMessage.IsSuccessStatusCode)
            {
                return RedirectToAction("Index");
            }
            return View();
        }
        [HttpGet]
        public async Task<IActionResult> Update(int id)
        {
            var client = _httpClientFactory.CreateClient();
            var responseMessage = await client.GetAsync($"https://localhost:7096/api/Actor/{id}");
            if (responseMessage.IsSuccessStatusCode)
            {
                var jsonData = await responseMessage.Content.ReadAsStringAsync();
                var values = JsonConvert.DeserializeObject<ActorUpdateDto>(jsonData);
                return View(values);
            }
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Update(ActorUpdateDto actorUpdateDto)
        {
            var client = _httpClientFactory.CreateClient();
            var jsonData = JsonConvert.SerializeObject(actorUpdateDto);
            StringContent stringContent = new StringContent(jsonData, Encoding.UTF8, "application/json");
            var responseMessage = await client.PutAsync("https://localhost:7096/api/Actor/UpdateActor/", stringContent);
            if (responseMessage.IsSuccessStatusCode)
            {
                return RedirectToAction("Index");
            }
            return View();
        }

        public async Task<IActionResult> Delete(int id)
        {
            var client = _httpClientFactory.CreateClient();
            var responseMessage = await client.DeleteAsync($"https://localhost:7096/api/Actor/{id}");
            if (responseMessage.IsSuccessStatusCode)
            {
                return RedirectToAction("Index");
            }
            return View();
        }
    }
}

MovieProject.UI/Views/Actor/Create.cshtml
@model ActorAddDto
<div class="content">
    <div class="container-fluid">
        <h4 class="page-title">Aktör İşlemleri</h4>
        <div class="row">
            <div class="col-md-12">
                <form method="post" asp-action="Create" asp-controller="Actor">
                    <div class="card">
                        <div class="card-header">
                            <div class="card-title">Aktör Ekleme Sayfası</div>
                        </div>
                        <div class="card-body">
                            <div class="form-group">
                                <label for="Title">Aktör Adı</label>
                                <input type="text" class="form-control" asp-for="Name">
                            </div>
                        </div>
                        <div class="card-action">
                            <button class="btn btn-primary">Kaydet</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

MovieProject.UI/Views/Actor/Index.cshtml
@model List<ResultActorDto>

<table id="hospitalTable" class="table table-bordered">
    <thead>
        <tr>
            <th>Aktör Adı</th>
            <th>İşlemler</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>@item.Name</td>
                <td><a asp-action="Update" asp-controller="Actor" asp-route-id="@item.ActorId" class="btn mb-1 btn-rounded btn-outline-info">Güncelle</a></td>
                <td><a asp-action="Delete" asp-controller="Actor" asp-route-id="@item.ActorId" class="btn mb-1 btn-rounded btn-outline-danger">Sil</a></td>
            </tr>
        }
    </tbody>
</table>

<a asp-action="Create" asp-controller="Actor" class="btn mb-1 btn-rounded btn-outline-info">Yeni Aktör Ekle</a>

MovieProject.UI/Views/Actor/Update.cshtml
@model ActorAddDto
<div class="content">
    <div class="container-fluid">
        <h4 class="page-title">Aktör İşlemleri</h4>
        <div class="row">
            <div class="col-md-12">
                <form method="post" asp-action="Update" asp-controller="Actor">
                    <div class="card">
                        <div class="card-header">
                            <div class="card-title">Aktör Güncelleme Sayfası</div>
                        </div>
                        <div class="card-body">
                            <div class="form-group">
                                <label for="Title">Aktör Adı</label>
                                <input type="text" class="form-control" asp-for="Name">
                            </div>
                        </div>
                        <div class="card-action">
                            <button class="btn btn-primary">Kaydet</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>